# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:stretch
    working_directory: /go/src/github.com/qlik-oss/sense-installer
    steps:
      - checkout
      - run: make test
      - run: make build
  build_release:
    docker:
      - image: circleci/golang:stretch
    working_directory: /go/src/github.com/qlik-oss/sense-installer
    steps:
      - checkout
      - run: make test
      - run: make xbuild-all
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG}  /go/src/github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/bin/${CIRCLE_TAG}/
workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
  build_release:
    jobs:
      - build_release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

