name: Build Sense installer

on: [pull_request]

jobs:

  test:
    name: Test
    env:
      CGO_ENABLED: 0
    strategy:
      matrix:
        go: [1.13.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2-beta
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v2

    - name: setup make (Windows)
      if: matrix.os == 'windows-latest'
      run: choco install make -y

    - run: make test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v2-beta
      with:
        go-version: 1.13

    - uses: actions/checkout@v2

    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - run: make xbuild-all
