name: Release Sense installer binaries

on: 
  push:
    tags:
      - 'v*.*.*'

jobs:

  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v2-beta
      with:
        go-version: 1.13

    - uses: actions/checkout@v2
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* # Needed in makefile for versioning

    - run: make test
    - run: make xbuild-all

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: bin/**/*
